version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "gt-football"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: fastapi-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: local
      LOCAL_DATABASE_URL: mysql+asyncmy://root:password@mysql-local:3306/gt-football
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
